---
fixtures:
  repositories:
    simp_apache: "https://github.com/simp/pupmod-simp-apache"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    iptables: "https://github.com/simp/pupmod-simp-iptables"
    stdlib: "https://github.com/simp/puppetlabs-stdlib"
    pki: "https://github.com/simp/pupmod-simp-pki"
    auditd: "https://github.com/simp/pupmod-simp-auditd"
    augeasproviders_grub: "https://github.com/simp/augeasproviders_grub"
    augeasproviders_core: "https://github.com/simp/augeasproviders_core"
    rsync: "https://github.com/simp/pupmod-simp-rsync"
    rsyslog: "https://github.com/simp/pupmod-simp-rsyslog"
    logrotate: "https://github.com/simp/pupmod-simp-logrotate"
    simpcat: "https://github.com/simp/pupmod-simp-concat"
  symlinks:
    kibana: "#{source_dir}"
